#!/usr/bin/env python3
"""
Post-process the SVGs generated by Platane/snk (github-snake.svg and github-snake-dark.svg)
to add month labels above, weekday labels (Mon, Wed, Fri) on the left, total contributions count
on the bottom-left, and a Less->More legend on the bottom-right.
"""
import datetime
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
CONTRIB_PATH = os.path.join(HERE, "..", "data", "contributions.json")
SNAKE_PATHS = [
    os.path.join(HERE, "..", "github-snake.svg"),
    os.path.join(HERE, "..", "github-snake-dark.svg")
]

def level_for(count):
    if count == 0:
        return 0
    if count <= 5:
        return 1
    if count <= 15:
        return 2
    if count <= 30:
        return 3
    if count <= 50:
        return 4
    return 5

def build_grid(days):
    first = datetime.date.fromisoformat(days[0]["date"])
    lead_pad = (first.weekday() + 1) % 7  # sunday=0
    grid = []
    col = [None] * lead_pad
    for d in days:
        date = datetime.date.fromisoformat(d["date"])
        weekday = (date.weekday() + 1) % 7
        while len(col) < weekday:
            col.append(None)
        col.append((d["date"], d["count"], level_for(d["count"])))
        if len(col) == 7:
            grid.append(col)
            col = []
    if col:
        while len(col) < 7:
            col.append(None)
        grid.append(col)
    return grid

def post_process_file(file_path, data):
    if not os.path.exists(file_path):
        print(f"File not found: {file_path}")
        return

    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Find the style content to determine palette and theme
    style_match = re.search(r"<style>(.*?)</style>", content, re.DOTALL)
    if not style_match:
        print(f"No style tag found in {file_path}")
        return
        
    style_text = style_match.group(1)
    
    # Extract color variables from SVG style tag
    c0 = re.search(r"--c0:\s*(#[0-9a-fA-F]+)", style_text)
    c1 = re.search(r"--c1:\s*(#[0-9a-fA-F]+)", style_text)
    c2 = re.search(r"--c2:\s*(#[0-9a-fA-F]+)", style_text)
    c3 = re.search(r"--c3:\s*(#[0-9a-fA-F]+)", style_text)
    c4 = re.search(r"--c4:\s*(#[0-9a-fA-F]+)", style_text)
    ce_match = re.search(r"--ce:\s*(#[0-9a-fA-F]+)", style_text)
    
    # Defaults
    palette = ["#161b22", "#01311f", "#034525", "#0f6d31", "#00c647"]
    theme = "dark"
    
    if c0 and c1 and c2 and c3 and c4:
        palette = [c0.group(1), c1.group(1), c2.group(1), c3.group(1), c4.group(1)]
        
    if ce_match:
        ce = ce_match.group(1).lower()
        if ce in ["#ebedf0", "#eee", "#ebedf00a"]:
            theme = "light"
            
    if theme == "dark":
        TEXT_COLOR = "#e6edf3"
        MUTED_COLOR = "#7d8590"
    else:
        TEXT_COLOR = "#24292f"
        MUTED_COLOR = "#57606a"

    # Extract all rects (elements with class c, u, s)
    rects = re.findall(r"(<rect.*?>)", content)
    if not rects:
        print(f"No rect elements found in {file_path}")
        return

    inner_elements = "\n".join(rects)
    
    # Grid math
    days = data["days"]
    grid = build_grid(days)
    
    month_labels = []
    seen_months = set()
    prev_ci = -999
    for ci, column in enumerate(grid):
        first_date = None
        for cell in column:
            if cell is not None:
                first_date = datetime.date.fromisoformat(cell[0])
                break
        if first_date is None:
            continue
        
        key = (first_date.year, first_date.month)
        should_label = False
        if key not in seen_months:
            if ci == 0:
                should_label = True
            elif first_date.day <= 7:
                if ci - prev_ci >= 2:
                    should_label = True
        
        if should_label:
            seen_months.add(key)
            month_labels.append((ci, first_date.strftime("%b")))
            prev_ci = ci

    # Dimensions
    PAD_L = 10
    PAD_R = 10
    PAD_T = 10
    PAD_B = 10
    LEFT_LABEL_W = 30
    TOP_LABEL_H = 20
    CELL = 12
    STEP = 16
    GAP = 4
    
    grid_top = PAD_T + TOP_LABEL_H
    grid_left = PAD_L + LEFT_LABEL_W
    art_w = len(grid) * STEP
    
    canvas_w = grid_left + art_w - GAP + PAD_R
    canvas_h = 218
    footer_y = 196
    
    # Generate labels elements
    label_elements = []
    for ci, label in month_labels:
        x = grid_left + ci * STEP
        label_elements.append(f'<text x="{x}" y="{PAD_T + 14}" fill="{MUTED_COLOR}" font-size="10">{label}</text>')
        
    for wi, wname in [(1, "Mon"), (3, "Wed"), (5, "Fri")]:
        y = grid_top + wi * STEP + CELL * 0.78
        label_elements.append(f'<text x="{PAD_L}" y="{y:.1f}" fill="{MUTED_COLOR}" font-size="9">{wname}</text>')

    # Total contributions count
    total = data["total_contributions"]
    label_elements.append(f'<text x="{grid_left}" y="{footer_y + CELL*0.8:.1f}" fill="{TEXT_COLOR}" font-size="12" font-weight="700">'
                          f'{total:,} contributions in the last year</text>')

    # Legend Less->More
    grid_right = grid_left + art_w - GAP
    leg_width = 136
    leg_x = grid_right - leg_width
    label_elements.append(f'<text x="{leg_x}" y="{footer_y + CELL*0.8:.1f}" fill="{MUTED_COLOR}" font-size="10" text-anchor="start">Less</text>')
    lx = leg_x + 28
    for lvl, color in enumerate(palette):
        label_elements.append(f'<rect x="{lx}" y="{footer_y}" width="{CELL}" height="{CELL}" rx="2.5" fill="{color}"/>')
        lx += STEP
    label_elements.append(f'<text x="{lx + 3}" y="{footer_y + CELL*0.8:.1f}" fill="{MUTED_COLOR}" font-size="10" text-anchor="start">More</text>')

    # Build new SVG
    new_svg = []
    new_svg.append(f'<svg viewBox="0 0 {canvas_w} {canvas_h}" width="{canvas_w}" height="{canvas_h}" xmlns="http://www.w3.org/2000/svg" '
                   f'font-family="-apple-system, BlinkMacSystemFont, \'Segoe UI\', Helvetica, Arial, sans-serif, \'Apple Color Emoji\', \'Segoe UI Emoji\'">')
    new_svg.append(f"<desc>Generated with snk and post-processed</desc>")
    new_svg.append(f"<style>{style_text}</style>")
    new_svg.append("\n".join(label_elements))
    new_svg.append(f'<g transform="translate(38, 28)">')
    new_svg.append(inner_elements)
    new_svg.append(f'</g>')
    new_svg.append(f'</svg>')
    
    final_svg_content = "\n".join(new_svg)
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(final_svg_content)
    print(f"wrote {file_path} ({len(final_svg_content)} bytes)")

if __name__ == "__main__":
    if not os.path.exists(CONTRIB_PATH):
        print(f"Contributions JSON not found at {CONTRIB_PATH}")
        exit(1)
        
    with open(CONTRIB_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)
        
    for p in SNAKE_PATHS:
        post_process_file(p, data)
